- hosts: all
  become: true
  user: ansible
  gather_facts: false
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt update'

- hosts: awx
  become: true
  user: ansible
  gather_facts: true
  roles:
  - {role: instalandoK3s}
