- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./awx-deploy.yml
    dest: /tmp
    mode: '0755'

- name: Subindo o manifesto AWX
  shell: kubectl apply -f /tmp/awx-deploy.yml && watch kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator" && kubectl get secret awx-admin-password -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'